### ISSUE TITLE
Empty lines aren't shown

### ISSUE THREAD

**Issue by alienlebarge** [andywer/postcss-debug#17]
The snapshots doesn't show empty lines.

For example, here's a piece of my initial code:

``` css
...
/**
 * SETINGS
 */

@import "settings/_settings.global.css";
@import "settings/_settings.fontface.css";
@import "settings/_settings.responsive.css";





/**
 * TOOLS
 */

@import "tools/_tools.mixins.css";
@import "tools/_tools.clearfix.css";





/**
 * GENERIC
 */

@import "generic/_generic.box-sizing.css";
@import "normalize.css";
@import "generic/_generic.reset.css";
@import "generic/_generic.shared.css";
...
```

and here's what postcss-debug show:

![napkin 3 13 09 16 10 54 26 am](https://cloud.githubusercontent.com/assets/611234/18467461/626ba2b0-79a0-11e6-95ff-9dd30cee240e.png)

**Comment by andywer** [comment]
Unfortunately this is a postcss bug: postcss/postcss-import#206

But I will see what I can do...

**Comment by andywer** [comment]
So this is basically the reason for the missing blank lines: https://github.com/postcss/postcss/issues/364

But I might be able to work around that issue...

**Comment by andywer** [comment]
@alienlebarge Could you test the current `master` branch if it works for you as expected now?

**Comment by alienlebarge** [comment]
@andywer Works great ! 👍 
Thanks for the fix !
