### ISSUE TITLE
Resizing of the snapshot view isn't applied in v0.4.1

### ISSUE THREAD

**Issue by alienlebarge** [andywer/postcss-debug#18]
The change made in the Pull Request #16 aren't actives in version 0.4.1.

As I see, the styles are inlined. Perhaps a build is missing.

**Comment by alienlebarge** [comment]
![napkin 3 14 09 16 8 15 59 am](https://cloud.githubusercontent.com/assets/611234/18501818/689ea23c-7a53-11e6-9f5d-bd948815fa3e.png)

**Comment by andywer** [comment]
I am gonna take care of it.

The upside is: I would have released a new hotfix version for the blank lines issue, anyway 😉

**Comment by andywer** [comment]
I guess it's just a missing `npm run build` in the webdebugger.

**Comment by andywer** [comment]
Just fixed it and released 0.4.2. Please verify if everything is working fine for you now 😉

**Comment by alienlebarge** [comment]
Everything is fine !
👍
